version: "3.8"

services:
  gopro-fiber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gopro-fiber
    ports:
      - 5000:5000
    networks:
      - dev-network
    volumes:
      - ./:/app

networks:
  dev-network:
    driver: bridge
